config/routes.rb
Rails.application.routes.draw do

      resources :restaurants
      root 'welcome#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	validates :name, presence: true,
                    length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ActionController::Base
	def index
		@restaurant = Restaurant.all
	end

	def new
		@restaurant = Restaurant.new
	end

def create
		
		@restaurant = Restaurant.new(user_params)
		    if @restaurant.save
		    	redirect_to restaurant_path(@restaurant.id)
    		else
      	flash[:alert] = "Something went wrong! Please try again!"

     	render 'new'
    end
end

	# end
def show
  @restaurant = Restaurant.find(params[:id])
end


def update
  @restaurant = Restaurant.find(params[:id])
 
  if @restaurant.update(user_params)
    redirect_to @restaurant
  else
    render 'edit'
  end
end


	def edit
  		@restaurant = Restaurant.find(params[:id])
	end

	def destroy
		  @restaurant = Restaurant.find(params[:id])
  		  @restaurant.destroy
  		   redirect_to restaurants_path
	end

	
	private
	  def user_params
	  	params.require(:restaurant).permit(:name, :street_address_1, :street_address_2, :city, :state, :zipcode, :phonenumber, :website)
  	  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base
	def index
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestaurantApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
<% if @restaurant.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited
      this restaurant from being saved:</h2>
    <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
</div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :street_address_1%><br>
    <%= f.text_area :street_address_1 %>
  </p>

    <p>
    <%= f.label :street_address_2 %><br>
    <%= f.text_area :street_address_2 %>
  </p>

  <p>
    <%= f.label :city %><br>
    <%= f.text_area :city %>
  </p>

  <p>
    <%= f.label :state %><br>
    <%= f.text_area :state %>
  </p>

  <p>
    <%= f.label :zipcode %><br>
    <%= f.text_area :zipcode %>
  </p>

   <p>
    <%= f.label :phone_number %><br>
    <%= f.text_area :phone_number %>
  </p>
     <p>
    <%= f.label :website %><br>
    <%= f.text_area :website %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>
<h2>Please edit the restaurant listing below</h2>
<%= render 'form' %>
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'Main Page', controller: 'welcome' %> 
<%= link_to 'New Restaurant', new_restaurant_path %>

<h1>Listing Restaurants</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>City</th>
  </tr>
 
  <% @restaurant.each do |restaurant| %>
    <tr>
      <td><%= restaurant.name %></td>
      <td><%= restaurant.city %></td>
    <td><%= link_to 'Show', restaurant_path(restaurant) %></td>
    <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
    <td><%= link_to 'Destroy', restaurant_path(restaurant), method: :delete, data: { confirm: 'Are you sure?' } %></td> 
    </tr>
  <% end %>
</table>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<h2>Please enter the form below:</h2>
<%= render 'form' %>
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<h1>Restaurant Details</h1>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>
 
<p>
  <strong>Address 1:</strong>
  <%= @restaurant.street_address_1 %>
</p>

<p>
  <strong>Address 2:</strong>
  <%= @restaurant.street_address_2 %>
</p>
<p>
  <strong>City</strong>
  <%= @restaurant.city %>
</p>
<p>
  <strong>State</strong>
  <%= @restaurant.state %>
</p>
<p>
  <strong>Zip Code</strong>
  <%= @restaurant.zipcode { |row|  } %>
</p>
<p>
  <strong>Phone number</strong>
  <%= @restaurant.phone_number { |row|  } %>
</p>
<p>
  <strong>Website</strong>
  <%= @restaurant.website { |row|  } %>
</p>


<%= link_to 'Back', restaurants_path %>
<%= link_to 'Edit', edit_restaurant_path(@restaurant) %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Restaurants', controller: 'restaurants' %> 
<%= link_to 'New Restaurant', new_restaurant_path %>	